s = set()
# print(type(s))
# s_from_list = set([1, 2, 3, 4, 5])
# print(s_from_list)
# print(type(s_from_list))
s.add(1)
s.add(2)
s1 = set([1, 2, 3])
sr = s.union(s1)
print(s, s1, "Union is: ", sr)
sr = s.intersection(s1)
print(s, s1, "intersection is: ", sr)
