import numpy as np
a = np.array([1, 4, 45, 66])
# print(a[0])
# print(a[1])
# print(a[2])
# print(a[3])
# for i in a:
#     print("This is just values", i)
# print("This is just that how many daimantion there are: ", a.ndim)
a1 = np.array([[3, 4, 5], [6, 7, 5]])
# print(a1.size)
# print(a1.size*a1.itemsize)
# print(a1)
# print("This is value on [1][1] dimantion:", a1[1][1])
# print("This is value on [0][1] dimantion:", a1[0][1])
# print("This is value on [0][2] dimantion:", a1[0][2])
# print("This is value on [1][2] dimantion:", a1[1][2])
# print("This is just that how many daimantion there are: ", a1.ndim)

a2 = np.array([[2, 5, 6], [6, 7, 8], [10, 80, 60]], dtype=np.int64)
# print("This is values of a2: \n", a2)
# print(a2.size)
# print("This is size of one item in array: ", a2.itemsize)
# print("This is just dataType of this values: ", a2.dtype)
a3 = np.array([[2, 5, 6], [6, 7, 8], [10, 80, 60]], dtype=np.float32)
# print("This is values of a3: \n", a3)
# print("This is size of one item in array: ", a3.itemsize)
# print("This is just dataType of this values: ", a3.dtype)
# print(a3.size)
# print(a3.shape)

a4 = np.array([[2, 5, 6], [6, 7, 8], [10, 80, 60]], dtype=complex)
# print("This is a4:\n", a4)
#
a5 = np.zeros((4, 4))
# print(a5)
a5 = np.ones((3, 4))
# print(a5)
l1 = range(1, 6)
# print(l1[1])
l2 = np.arange(0, 6)
# print(l2)
# print(l2[2])
l3 = np.linspace(1, 5, 50)
# print(l3)
#
a6 = np.array([[3, 4], [5, 5], [6, 7]])
print("This is shape of a6: ", a6.shape)
print("This is a6: \n", a6)
#
# print("This is shape of a6:\n ", a6.reshape(2, 3))
# print("This is shape of a6:\n ", a6.reshape(1, 6))
# print("This is shape of a6:\n ", a6.reshape(6, 1))
# print("This is shape of a6:\n ", a6.ravel())
# print("Minimum Number in a6 array: ", a6.min())
# print("Maximum Number in a6 array: ", a6.max())
print("Sum of all in a6 array: ", a6.sum())
# print(a6)
# print("Sum of axis in a6 array: ", a6.sum(axis=0))
# print("Sum of axis in a6 array: ", a6.sum(axis=1))
print(np.sqrt(a6))
i#